workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Pago-OAS:
        inputs:
            - location: https://api.pago.sh/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/security.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/type_parameter.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/product_price_discriminator.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/read_only.yml
        registry:
            location: registry.speakeasyapi.dev/pago/pago/pago-oas
targets:
    pago:
        target: ruby
        source: Pago-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/pago/pago/pago-api-ruby-code-samples
            blocking: false
